### PR TITLE
Fixed STM32F746-Discovery project build

### PR DESCRIPTION
**Pull request by Tuetuopay**
Even the ChibiOS version of the demo project includes the STM32Cube HAL, but the makefile does not, including it only for the RAW32 OS. Thus, moved it outside of the RAW32-only section.

### CODE REVIEW

**Comment by cpu20** [comment]
You should not push any changes here. I am using this repo to figure out the problem when combining uGFX and Chibios on the STM32F746-DISCO platform.
Any help to the project is appreciated on the official git page! git.ugfx.io

**Comment by Tuetuopay** [comment]
Oooops my bad, I forgot to check whether you introduced this problem, and it turns out it is present upstream.

However, this repo could be considered as a "patch" for upstream to fix this board.

(PS : I am REALLY interested in making this board working, I'll give it a shot)

**Comment by cpu20** [comment]
Yesterday I finally got it working. You can use this version of uGFX with ChibiOS_17.1.3 and the STM32F746-disco board and it should work. If you find any problems let me know!

**Comment by Tuetuopay** [comment]
I'll give it a shot as soon as I am home ! Judging by your commits, it looks like the problem did reside in the clock settings, as suspected in the ChibiOS forum thread. Great work mate !

**Comment by Tuetuopay** [comment]
Yup, I confirm it's working for me with chibios 16.1 ! Just by playing with the demo, I could not see any major difference between the ChibiOS and the RAW32 version (except for glitches common to the two).

If you need any help for the upstream merge, I'd be glad to help.

PS: this MR still holds for upstream :P Though I can directly send it upstream as it is still in there :(

**Comment by cpu20** [comment]
I looked further into your pull request and I am not entirely sure if the HAL inclusion should be done in the board.mk or if it should be done in the project makefile. Maybe you should open a forum post on the ugfx forums to ask for further instructions.

**Comment by Tuetuopay** [comment]
I guess it should be done in the board.mk as it is already present in it, I just moved it out of the Raw32-only section. Anyways, I will still do just to be sure with them.

**Comment by Tuetuopay** [comment]
I just re-looked at the file needing it, the µGFX-provided SDRAM init code in `stm32f746g_discovery_sdram.c` includes the ST-provided `stm32f7xx_hal_rcc.h` (and possibly many others). My bet would be that is should be in `board.mk`.

The only question I have left is whether we make ALL OSes include the ST HAL or only ChibiOS and RAW32. I'd say all of them since the external SDRAM is more or less mandatory to have a correct color depth on the screen.

**Pull request merged**
